# for local development
version: '3.7'
networks:
  network-custom:
    name: theeduaid_frontend
    external: true
services:
  dev-quasar-admin:
    container_name: dev-eduaid-admin
    build:
      context: .
    ports:
      - "${NGINX_HOST_PORT}:80"
    networks:
      - network-custom
